### ISSUE TITLE
VAD solutions?

### ISSUE THREAD

**Issue by wdbdesign** [dalehumby/rhasspy-config#1]
Thanks for posting this.  It's been a real inspiration!  I've got something very similar set up, and took some inspiration from your "Using GPT3 for intent recognition" post.  I'm currently struggling with VAD.  Is there something you use for VAD, or are you just using a fixed time window?  I'm using Whisper-Live and have toyed with the idea of running the current query through a local "is this a complete sentence" model, but haven't found anything fast or reliable enough yet.  I'm currently testing out picovoice's Cobra VAD solution, but haven't been able to nail down a reliable threshold.

**Comment by dalehumby** [comment]
Hey! Sorry for taking some time to respond. It's been a while since I used Rhasspy, so I cannot remember all my VAD settings, but I wasn't doing anything fancy, just using the built in models to detect when there was no voice, and tweaked the settings so it didn't stop too early (like when pausing while asking the assistant something) or take too long after I had stopped speaking.

I think your idea of using Whisper-Live + "is this query complete?" interesting. Maybe you could build your own model or fine-tune an existing model? The good people on https://community.rhasspy.org/ might have some ideas.

What I struggled most with was reliable wake word detection. I found that the assistant had false positive tiggers – it would trigger even when the room was silent, or something was on the TV or if music was playing in the background. I used openwakeword, and dockerised that so I could run detection on a beefier computer than the Pi. (See https://github.com/dalehumby/openWakeWord-rhasspy)

If I was going to restart I'd probably investigate what was built into Home Assistant, since that also has integrations into various LLMs, and the voice part is built by the same developer who built Rhasspy.

**Comment by wdbdesign** [comment]
Thanks for responding!  I have been using picovoice's porcupine on a pi4b,
and it seems to pick up the wake word 90% of the time.  No false positives
yet.  For VAD I'm trying out picovoice's solution.  It turns out I had a
bug and wasn't always filling the buffer completely, which led to most of
my issues.  I did try running Mistral-7b locally to determine sentence
completeness but it was slow and not very accurate.  Maybe with a beefier
GPU and more VRAM, but I'll set that aside for now and experiment with it
more later.
Thanks again for taking the time to respond!
